base = "ocean"
syntax = "base16-ocean.dark"

[ui]
toc_bg = "#16161e"
toc_border = "#292e42"
content_bg = "#1a1b26"
scrollbar_hover = "#7aa2f7"
status_bg = "#16161e"
status_separator = "#565f89"
status_brand_fg = "#16161e"
status_brand_bg = "#7aa2f7"
status_filename_fg = "#c0caf5"
status_filename_bg = "#292e42"
status_watch_fg = "#9ece6a"
status_watch_bg = "#1f2b1e"
status_reloaded_fg = "#16161e"
status_reloaded_bg = "#9ece6a"
status_search_fg = "#e0af68"
status_search_bg = "#292e42"
status_success_fg = "#9ece6a"
status_success_bg = "#1f2b1e"
status_warning_fg = "#e0af68"
status_error_fg = "#f7768e"
status_error_bg = "#37222c"
status_shortcut_fg = "#565f89"
status_percent_fg = "#7aa2f7"
toc_hover_fg = "#c0caf5"
toc_header_fg = "#565f89"
toc_active_bg = "#292e42"
toc_inactive_bg = "#16161e"
toc_accent = "#7aa2f7"
toc_index_inactive = "#545c7e"
toc_primary_active = "#c0caf5"
toc_primary_inactive = "#a9b1d6"
toc_secondary_inactive = "#545c7e"
toc_secondary_text_active = "#a9b1d6"
toc_secondary_text_inactive = "#565f89"

[markdown]
search_highlight_bg = "#3b4261"
search_match_bg = "#e0af68"
code_gutter = "#545c7e"
blockquote_marker = "#565f89"
list_level_1 = "#9ece6a"
list_level_2 = "#7dcfff"
list_level_3 = "#bb9af7"
ordered_list = "#e0af68"
table_border = "#3b4261"
table_separator = "#292e42"
table_header = "#7aa2f7"
table_cell = "#c0caf5"
heading_1 = "#7aa2f7"
heading_2 = "#9ece6a"
heading_3 = "#7dcfff"
heading_4 = "#bb9af7"
heading_other = "#ff9e64"
heading_underline = "#292e42"
code_frame = "#545c7e"
code_label = "#565f89"
inline_code_fg = "#ff9e64"
inline_code_bg = "#292e42"
rule = "#292e42"
link_icon = "#7dcfff"
link_text = "#7dcfff"
link_hover = "#b4f9f8"
blockquote_text = "#a9b1d6"
text = "#c0caf5"
strong_text = "#c0caf5"
latex_inline_fg = "#bb9af7"
latex_inline_bg = "#292e42"
latex_block_fg = "#bb9af7"
mermaid_keyword = "#ff9e64"
mermaid_arrow = "#7dcfff"
mermaid_label = "#9ece6a"
mermaid_block_fg = "#c0caf5"
mark_fg = "#1a1b26"
mark_bg = "#e0af68"
task_checked = "#9ece6a"
task_unchecked = "#565f89"
alert_note = "#7aa2f7"
alert_tip = "#9ece6a"
alert_important = "#bb9af7"
alert_warning = "#e0af68"
alert_caution = "#f7768e"
