alias ..='cd ..'
alias t='cd "$(mktemp -d)"'

alias st='git status'
alias ck='git checkout'
alias br='git branch -vv'
alias co='git commit'
alias di='git -c delta.side-by-side=true diff'
alias gg='git graph -n 15'

alias c='chezmoi'
alias m='multipass'

alias ls='exa -gF --icons --git --color=always -la'
alias grep='rg'
alias find='fd'
alias top='btm'
alias htop='btm'
alias df='duf'
alias du='duf'
alias ping='gping'
