#!/bin/bash

os=
if [[ `uname` = Darwin ]]; then
  os=mac
elif [[ `uname -r` =~ microsoft ]]; then
  os=wsl
else
  os=linux
fi

case $os in
  mac)
    exec git credential-osxkeychain "$@"
    ;;
  wsl)
    exec /mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe "$@"
  ;;
  linux)
    exec git credential-cache --timeout 86400 "$@"
  ;;
esac
