#!/usr/bin/env bash
set -euo pipefail

use_gh() {
  local output
  if ! output=$(gh auth switch --user $1 2>&1); then
    local exit_code=$?

    log_error "failed to switch GitHub account to $1"
    log_error "$output"

    return $exit_code
  fi
}

use_aws() {
  export AWS_PROFILE="$1"
  export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
  export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
}
