#!/usr/bin/env bash
set -euo pipefail

use_gh() {
  local output
  if ! output=$(gh auth switch --user $1 2>&1); then
    local exit_code=$?

    log_error "failed to switch GitHub account to $1"
    log_error "$output"

    return $exit_code
  fi
}

use_aws() {
  export AWS_PROFILE="$1"
}
