#!/bin/bash
set -x

dotdir_path="${HOME}/dotfiles"

function Setup.symlink() {
    local target=$1
    local to=${2:-"${HOME}/${target}"}
    ln -sfn ${dotdir_path}/${target} ${to}
}

################################################################################

: 'copy git config file' && {
    Setup.symlink git/gitconfig ~/.gitconfig
    Setup.symlink git/gitignore_global ~/.gitignore_global
}

: 'copy vimrc & gvimrc' && {
    mkdir -p ~/.vim
    rm -f ~/.vimrc ~/.gvimrc ~/.viminfo
    Setup.symlink vim/vimrc ~/.vim/vimrc
    Setup.symlink vim/gvimrc ~/.vim/gvimrc
    Setup.symlink vim/snippets ~/.vim/snippets
    Setup.symlink vim/templates ~/.vim/templates
    Setup.symlink vim/ftplugin ~/.vim/ftplugin
    Setup.symlink vim/syntax ~/.vim/syntax
}

: 'install neobundle & vim plugins' && [[ ! -e ~/.vim/bundle/neobundle.vim ]] && {
    mkdir -p ~/.vim/bundle
    git clone https://github.com/Shougo/vimproc.vim ~/.vim/bundle/vimproc.vim
    (cd ~/.vim/bundle/vimproc.vim && make)
    git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
}

: 'install zplug' && [[ ! -e ~/.zplug/init.zsh ]] && {
    mkdir -p ~/.zplug
    git clone https://github.com/zplug/zplug ~/.zplug
}

: 'copy zshenv & zshrc, peco-functions' && {
    Setup.symlink zsh/zshenv ~/.zshenv
    Setup.symlink zsh/zshrc ~/.zshrc
    mkdir -p ~/.zsh/site-functions
    Setup.symlink zsh/peco-functions.zsh ~/.zsh/site-functions/peco-functions.zsh
}

: 'copy .tmux.conf' && {
    Setup.symlink .tmux.conf
}

: 'other conig file' && {
    mkdir -p ~/.config/peco
    Setup.symlink etc/peco.json ~/.config/peco/config.json
    Setup.symlink etc/ctags ~/.ctags
    Setup.symlink bin
}
