#!/bin/bash

dotdir_path="${HOME}/dotfiles"

function Setup.symlink() {
    local target=$1
    local to=${2:-"${HOME}/${target}"}
    [[ -f "${dotdir_path}/${target}" ]] && ln -sfn ${dotdir_path}/${target} ${to}
}

################################################################################

: 'copy git config file' && {
    Setup.symlink .gitconfig
    Setup.symlink .gitignore_global
}

: 'copy vimrc & gvimrc' && {
    mkdir -p ~/.vim
    rm -f ~/.vimrc ~/.gvimrc ~/.viminfo
    Setup.symlink .vim/vimrc ~/.vim/vimrc
    Setup.symlink .vim/gvimrc ~/.vim/gvimrc
}

: 'copy zshenv & zshrc' && {
    Setup.symlink .zshenv
    Setup.symlink .zshrc
}

: 'change login shell' && {
    sudo chsh -s $(which zsh) $USER
}

: 'copy .tmux.conf' && {
    Setup.symlink .tmux.conf
}
