services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/nonroot/.dotfiles
    environment:
      - TERM
      - COLORTERM
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
    secrets:
      - github_token
    volumes:
      - .:/home/nonroot/.dotfiles
    tty: true

secrets:
  github_token:
    environment: GITHUB_TOKEN
