experimental_monorepo_root = true
monorepo.config_roots = ["packages/*"]

[settings]
lockfile = true

[settings.github]
credential_command = "gh auth token"

[tools]
lefthook = "2.0.15"
"github:convco/convco" = "0.6.2"

[hooks]
postinstall = "lefthook install"

[tasks."chezmoi:diff"]
description = "chezmoi diff"
run = "chezmoi diff --exclude scripts"

[tasks."chezmoi:apply"]
description = "chezmoi apply"
run = "chezmoi apply"
