[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'osyo-manga/vim-precious'
hook_add = '''
    let g:precious_enable_switchers = {
        \   '*': {
        \       'setfiletype': 1,
        \   },
        \   'help': {
        \       'setfiletype': 0,
        \   },
        \   'markdown': {
        \       'setfiletype': 0,
        \   },
        \ }
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
    if !has('gui_running') && !&termguicolors
        let g:hybrid_custom_term_colors = 1
    endif

    set fillchars+=vert:│
    set bg=dark

    augroup ModifyColor
        autocmd VimEnter * nested colorscheme hybrid_reverse
        autocmd Colorscheme hybrid_reverse hi! link agitDiffAdd ModeMsg
        autocmd Colorscheme hybrid_reverse hi! link agitStatAdded ModeMsg
        autocmd Colorscheme hybrid_reverse hi! link agitDiffRemove WarningMsg
        autocmd Colorscheme hybrid_reverse hi! link agitStatRemoved WarningMsg
        autocmd Colorscheme hybrid_reverse hi! VertSplit guifg=#282a2e
        autocmd Colorscheme hybrid_reverse hi! EndOfBuffer ctermfg=0 guifg=#1d1f21
        autocmd Colorscheme hybrid_reverse hi! link GitGutterAdd ModeMsg
        autocmd Colorscheme hybrid_reverse hi! link GitGutterChange diffRemoved
        autocmd Colorscheme hybrid_reverse hi! link GitGutterDelete WarningMsg
        autocmd Colorscheme hybrid_reverse hi! link GitGutterChangeDelete WarningMsg
        autocmd Colorscheme hybrid_reverse hi! NERDTreeDir ctermfg=0 guifg=#81a2be
        autocmd Colorscheme hybrid_reverse hi! NERDTreeDirSlash ctermfg=0 guifg=#81a2be
        autocmd Colorscheme hybrid_reverse hi! NERDTreeOpenable ctermfg=0 guifg=#1d1f21
        autocmd Colorscheme hybrid_reverse hi! NERDTreeClosable ctermfg=0 guifg=#1d1f21
        autocmd Colorscheme hybrid_reverse hi! User1 guifg=#1d1f21 guibg=#a54242
        autocmd Colorscheme hybrid_reverse hi! User2 guifg=#1d1f21 guibg=#5F5F87
        autocmd Colorscheme hybrid_reverse hi! ALEError guifg=#c5c8c6 guibg=#a54242
        autocmd Colorscheme hybrid_reverse hi! ALEErrorSign guifg=#a54242
        autocmd Colorscheme hybrid_reverse hi! ALEWarning guifg=#c5c8c6 guibg=#de935f
        autocmd Colorscheme hybrid_reverse hi! ALEWarningSign guifg=#de935f
    augroup END
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <C-n> :<C-u>NERDTreeToggle<CR>
    nnoremap <C-f> :<C-u>NERDTreeFind<CR>

    let g:NERDTreeMinimalUI = 1
    let g:NERDTreeMouseMode = 2
    let g:NERDTreeChDirMode = 1
    let g:NERDTreeHighlightCursorline = 0
    let g:NERDTreeIgnore = [
        \ 'node_modules',
        \ 'vendor',
        \ ]

    if dein#tap('vim-devicons')
        let g:webdevicons_enable_nerdtree = 1

        let g:DevIconsEnableFoldersOpenClose = 1
        let g:WebDevIconsUnicodeDecorateFolderNodes = 1
        let g:DevIconsDefaultFolderOpenSymbol = "\ue5fe\u00a0"
        let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = "\ue5ff\u00a0"

        let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol = "\uf0f6"
        let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
        let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['markdown'] = "\uf48a"
        let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['md'] = "\uf48a"

        let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
        let g:WebDevIconsNerdTreeGitPluginForceVAlign = 1
        let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
    endif
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    nnoremap <silent><space>h :<C-u>GitGutterLineHighlightsToggle<CR>
    nnoremap <silent><space>j :<C-u>GitGutterNextHunk<CR>
    nnoremap <silent><space>k :<C-u>GitGutterPrevHunk<CR>
'''

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'wavded/vim-stylus'

[[plugins]]
repo = 'timcharper/textile.vim'

[[plugins]]
repo = 'noprompt/vim-yardoc'

[[plugins]]
repo = 'sunaku/vim-ruby-minitest'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = '844196/smarty-syntax'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'Mundo'
hook_add = '''
    let g:mundo_width = 80
    let g:mundo_height = 60
    nnoremap <silent><F5> :<C-u>MundoToggle<CR>
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
on_cmd = 'GoUpdateBinaries'
hook_add = '''
    let g:go_fmt_command = 'goimports'
    let g:go_fmt_autosave = 1
    let g:go_gocode_unimported_packages = 1
'''
hook_post_update = '''
    GoUpdateBinaries
'''

[[plugins]]
repo = 'Shougo/vimproc'
hook_post_update = '''
    let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = 'markdown'
hook_add = '''
    let g:table_mode_corner='|'
    let g:table_mode_auto_align = 0
'''

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_cmd = 'Alignta'
hook_add = '''
    vnoremap <silent><C-p> :'<,'>Alignta <- $<CR>
'''

[[plugins]]
repo = '844196/previm'
rev = 'modified-for-me'
on_cmd = 'PrevimOpen'
hook_add = '''
    let g:previm_enable_realtime = 1
    let g:previm_disable_default_css = 0
    let g:previm_show_header = 0
'''

[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_map = '<Plug>(incsearch'
hook_add = '''
    let g:incsearch#magic = '\v'

    map / <Plug>(incsearch-forward)
    map ? <Plug>(incsearch-backward)
    map n <Plug>(incsearch-nohl-n)zz
    map N <Plug>(incsearch-nohl-N)zz
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>(anzu'
if = 'v:false'
hook_add = '''
    nmap * "zyiw:let @/ = @z<CR>:<C-u>set hlsearch<CR><Plug>(anzu-update-search-status)
    vmap * "zy:let @/ = @z<CR>:<C-u>set hlsearch<CR><Plug>(anzu-update-search-status)
    nmap <silent><Esc><Esc> <Plug>(anzu-clear-search-status):<C-u>nohlsearch<CR>

    if dein#tap('incsearch.vim')
        map n <Plug>(incsearch-nohl-n)<Plug>(anzu-update-search-status)zz
        map N <Plug>(incsearch-nohl-N)<Plug>(anzu-update-search-status)zz
    endif
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'less', 'vue']
hook_add = '''
    let g:user_emmet_settings = {
        \ 'lang' : 'ja',
        \ 'html': {'indentation': '  '},
        \ 'vue': {'indentation': '  '},
        \ }
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
    let g:unite_force_overwrite_statusline = 0
    let g:unite_enable_start_insert = 1
    let g:unite_enable_ignore_case = 1
    let g:unite_enable_smart_case = 1

    augroup unite_my_settings
        autocmd!
        autocmd Filetype unite nmap <silent><buffer><Esc><Esc> <Plug>(unite_exit)
        autocmd Filetype unite imap <silent><buffer><Esc><Esc> <Plug>(unite_exit)
        autocmd Filetype unite imap <silent><buffer><C-e> <End>
        autocmd Filetype unite imap <silent><buffer><C-k> <C-o>"_D
    augroup END

    if dein#tap('vim-devicons')
        let g:webdevicons_enable_unite = 0
    endif

    " menu
    function! GetTestFilePath(origin) abort
        if match(a:origin, '^tests/') >= 0
            return a:origin
        endif

        let s:result = a:origin
        for [s:match_pattern, s:replace_pattern] in [['^src/', 'tests/'], ['\.php$', 'Test.php']]
            let s:result = substitute(s:result, s:match_pattern, s:replace_pattern, '')
        endfor

        return s:result
    endfunction
    let g:unite_source_menu_menus = {
        \ 'shortcut': {},
        \ 'git': {},
        \ }
    let g:unite_source_menu_menus.shortcut.command_candidates = [
        \ ['Reopen search-buffer', 'UniteResume search-buffer'],
        \ ['Create quickrun php snippet buffer', 'enew | 0r ~/.vim/templates/php.template | set ft=php | QuickRun'],
        \ ['Delete all buffer', '%bd'],
        \ ['Show make task', 'Unite make/help'],
        \ ['Run test', "execute '!phpunit ' . GetTestFilePath(expand('%'))"],
        \ ['Open test file', "execute 'vsplit ' . GetTestFilePath(expand('%'))"],
        \ ['Run diff test', '!make diff_test'],
        \ ['Paste mode on', 'set paste!'],
        \ ['Edit vimrc', 'edit ~/dotfiles/vim/vimrc'],
        \ ['Edit local vimrc', 'edit ~/.local/vimrc'],
        \ ['Edit plugins.toml', 'edit ~/dotfiles/vim/plugins.toml'],
        \ ['Formating markdown table', "'<,'>Alignta 0:0 |"],
        \ ['Tablize', "'<,'>Tableize"],
        \ ]
    noremap <silent>S :<C-u>Unite menu:shortcut<CR>

    " make/help
    let s:make_help_source = {
        \ 'name': 'make/help',
        \ 'syntax': 'uniteSource__Make_Help',
        \ 'hooks': {},
        \ }
    function! s:make_help_source.gather_candidates(args, context)
        let s:candidate_map = map(systemlist('make help'), '{
            \ "task": split(substitute(v:val, "\\e\\[[0-9;]\\+[mK]", "", "g"), "\\s\\{2,\\}")[0],
            \ "description": split(substitute(v:val, "\\e\\[[0-9;]\\+[mK]", "", "g"), "\\s\\{2,\\}")[1],
            \ }')
        let s:padding = max(map(copy(s:candidate_map), 'strlen(v:val.task)'))
        return map(copy(s:candidate_map), '{
            \ "word": printf("%-" . s:padding . "S  --  %s", v:val.task, v:val.description),
            \ "soruce": "make/help",
            \ "kind": "command",
            \ "action__command": (v:val.description =~ "[cC][lL][eE][aA][rR]" ? "!sudo make" : "!make") . " " . v:val.task,
            \ }')
    endfunction
    function! s:make_help_source.hooks.on_syntax(args, context)
        syntax match uniteSource__Make_Help_Task /[a-zA-Z_-]\+\ze\s*--/
            \ contained containedin=uniteSource__Make_Help
        highlight! default link uniteSource__Make_Help_Task ModeMsg
    endfunction
    call unite#define_source(s:make_help_source)
'''

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = '''
    nnoremap <silent> U :<C-u>Unite outline -vertical -direction=belowright<CR>
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
    imap <expr><C-k> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<C-G>U<C-o>D"
    smap <expr><C-k> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<C-G>U<C-o>D"
    xmap <expr><C-k> neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<C-G>U<C-o>D"
    let g:neosnippet#snippets_directory = '~/.vim/snippets/'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_cmd = 'Ctags'
hook_add = '''
    let g:auto_ctags = 0
    let g:auto_ctags_directory_list = ['.git']
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_ignore_case = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#enable_enable_camel_case_completion = 1
    let g:neocomplete#keyword_patterns = {}
    let g:neocomplete#keyword_patterns._ = '\h\w*'
    let g:neocomplete#max_list = 20
    let g:neocomplete#enable_fuzzy_completion = 0
    let g:neocomplete#enable_auto_delimiter = 1
    let g:neocomplete#delimiter_patterns = {
        \ 'php': ['->', '::', '\']
        \ }
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {}
    let g:quickrun_config._ = {
        \ 'outputter/buffer/split': ':lefta vertical',
        \ 'outputter/buffer/close_on_empty': 0,
        \ 'runner': 'vimproc',
        \ 'runner/vimproc/updatetime': 60,
        \ }
    let g:quickrun_config['ruby.bundle'] = {
        \ 'command': 'bundle',
        \ 'cmdopt': 'exec ruby',
        \ 'exec': '%c %o %s'
        \ }
    let g:quickrun_config.json = {
        \ 'outputter/buffer/filetype': 'json',
        \ 'command': 'jq',
        \ 'cmdopt': '.',
        \ 'exec': 'cat %s | sed "s/[\\]\"/\"/g" |  %c %o',
        \ }
    let g:quickrun_config.sql = {
        \ 'command': 'mysql-wrapper',
        \ 'exec': 'cat %s | %c',
        \ 'outputter/buffer/filetype': 'sqloutput',
        \ }

    nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''

[[plugins]]
repo = 'lilydjwg/colorizer'
if = 'v:false'

[[plugins]]
repo = '844196/vim-splash'
rev = 'modified-for-me'
hook_add = '''
    let g:splash#path = expand('~/dotfiles/vim/splash')
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-operator-sequence'

[[plugins]]
repo = 'osyo-manga/vim-operator-highlighter'
hook_add = '''
let g:operator#highlighter#config = {
    \ 'clear_time': 120,
    \ 'group': 'SpellLocal',
    \ }
noremap <Plug>(yank) y
noremap <expr> y operator#sequence#map("\<Plug>(operator-highlighter-once)", "\<Plug>(yank)")
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    let g:fzf_layout = {
        \ 'down': '15'
        \ }

    function! GetClass(path) abort
        " pclass: ~/bin/pclass
        return substitute(system('pclass ' . expand(a:path)), "\n", '', 'g')
    endfunction
    function! SetClass(path) abort
        let s:old_register = {
            \ 'type': getregtype('"'),
            \ 'value': getreg('"'),
            \ }
        call setreg('"', GetClass(a:path), 'v')
        if (col('$') > 1 && col('.') != (col('$') - 1))
            execute 'normal! ""gp'
            startinsert
        else
            execute 'normal! ""p'
            startinsert!
        endif
        call setreg('"', s:old_register.value, s:old_register.type)
    endfunction
    function! SetClasses(paths) abort
        call append(line('.') - 1, map(a:paths, {_, p -> 'use ' . GetClass(p) . ';'}))
    endfunction

    " カレントディレクトリ以下のファイル全て
    nnoremap <silent><Leader><Leader> :<C-u>FZF<CR>
    " Git管理下ファイル + untracked
    nnoremap <silent><Leader>s :<C-u>GFiles?<CR>
    " 開いてるタブ
    nnoremap <silent><Leader>t :<C-u>Windows<CR>
    " 開いてるバッファ
    nnoremap <silent><Leader>b :<C-u>Buffers<CR>
    " Ag
    nnoremap <Leader>g :<C-u>Ag 
    " PHPクラス名補完 (use一括挿入と挿入モード用useなしバージョン)
    nnoremap <silent><C-x><C-x> :<C-u>call fzf#run(fzf#wrap('files', {'sink*': function('SetClasses')}))<CR>
    inoremap <silent><C-x><C-x> <Esc>:<C-u>call fzf#run(fzf#wrap('files', {'sink': function('SetClass')}))<CR>
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'wsdjeg/FlyGrep.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_php_phpcs_standard = 'ruleset.xml'
    let g:ale_php_phpmd_ruleset = 'phpmd.xml'
    let g:ale_sign_error = "\uf057"
    let g:ale_sign_warning = "\uf06a"
    let g:ale_lint_delay = 750
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    augroup StatuslineWorkaround
        autocmd Colorscheme hybrid_reverse hi! StatusLine guifg=#212325 guibg=#5f5f5f
        autocmd Colorscheme hybrid_reverse hi! StatusLineNC guifg=#212325
    augroup END

    let s:p = {'normal': {}, 'insert': {}, 'visual': {}, 'replace': {}, 'inactive': {}, 'tabline': {}}
    let s:p.normal.left = [['#5f5f5f', '#212325', 0, 0]]
    let s:p.normal.middle = s:p.normal.left
    let s:p.normal.right = s:p.normal.left
    let s:p.inactive.left = [['#373b41', '#212325', 0, 0]]
    let s:p.inactive.middle = s:p.inactive.left
    let s:p.inactive.right = s:p.inactive.left
    let s:p.tabline.tabsel = [['#5f5f5f', '#232528', 0, 0]]
    let s:p.tabline.left = [['#373b41', '#1d1f21', 0, 0]]
    let s:p.tabline.middle = [['#1d1f21', '#1d1f21', 0, 0]]
    let s:p.tabline.right = s:p.tabline.middle
    let g:lightline#colorscheme#simple#palette = s:p

    function! StatuslineGitBranch() abort
        let branch = fugitive#head('%')

        return branch == '' ? '' : "\uf418 " . branch
    endfunction

    function! StatuslineChangedLineCount() abort
        let diff = GitGutterGetHunkSummary()
        if diff == [0, 0, 0]
            return ''
        endif

        return "\uf440" . ' ' . '+' . diff[0] . ',~' . diff[1] . ',-' . diff[2]
    endfunction

    function! TablineWebdevicon(tabnum) abort
        let bufferList = tabpagebuflist(a:tabnum)
        let activeBuffer = bufferList[tabpagewinnr(a:tabnum) - 1]
        let activeFilename = bufname(activeBuffer)

        return WebDevIconsGetFileTypeSymbol(activeFilename)
    endfunction

    let g:lightline = {
        \ 'active': {
        \     'left': [[
        \         'filename',
        \         'modified',
        \     ]],
        \     'right': [[
        \         'fileformat',
        \         'fileencoding',
        \         'filetype',
        \         'statuslineGitBranch',
        \         'statuslineChangedLineCount',
        \     ]],
        \ },
        \ 'inactive': {
        \     'left': [[
        \         'filename',
        \         'modified',
        \     ]],
        \     'right': [],
        \ },
        \ 'tab': {
        \     'active': [
        \         'tablineWebdevicon',
        \         'filename',
        \         'modified',
        \     ],
        \     'inactive': [
        \         'tablineWebdevicon',
        \         'filename',
        \         'modified',
        \     ],
        \ },
        \ 'component': {
        \     'filename': '%f',
        \ },
        \ 'component_function': {
        \     'statuslineGitBranch': 'StatuslineGitBranch',
        \     'statuslineChangedLineCount': 'StatuslineChangedLineCount',
        \     'webdevicon': 'WebDevIconsGetFileTypeSymbol',
        \ },
        \ 'tab_component_function': {
        \     'tablineWebdevicon': 'TablineWebdevicon',
        \ },
        \ 'colorscheme': 'simple',
        \ 'separator': {
        \     'left': '',
        \     'right': '',
        \ },
        \ 'subseparator': {
        \     'left': '',
        \     'right': '',
        \ },
        \ }
'''
