#!/bin/bash

sep="  "

currentPath="$(tmux display-message -p -F '#{pane_current_path}')"

currentBranch=''
if git -C "${currentPath}" rev-parse 2>/dev/null; then
    currentBranch=" $(git -C "${currentPath}" rev-parse --abbrev-ref HEAD)"

    changedFiles="$(git -C "${currentPath}" status --porcelain | awk '{files++}END{printf("%d files", files)}')"
    if [[ ! "${changedFiles}" == '0 files' ]]; then
        diffLines="$(git -C "${currentPath}" diff --numstat | awk 'NF==3{inc+=$1;dec+=$2;}END{printf("+%d,-%d",inc,dec)}')"
        changedFiles="${sep} ${changedFiles},${diffLines}"
    else
        changedFiles=''
    fi
fi

echo "${currentBranch}${changedFiles}"
