#!/bin/bash

os=
if [[ `uname` = Darwin ]]; then
  os=mac
elif [[ `uname -r` =~ microsoft ]]; then
  os=wsl
else
  os=linux
fi

# for wsl
# see: https://github.com/microsoft/WSL/issues/5065#issuecomment-835469034
show_correct_wsl_interop() {
  if [[ -z "$WSL_INTEROP" || -e "$WSL_INTEROP" ]]; then
    echo $WSL_INTEROP
    return
  fi

  local pid
  for pid in `pstree --numeric-sort --show-pids --show-parents $$ | grep -o -E '[0-9]+'`; do
    if [ -e "/run/WSL/${pid}_interop" ]; then
      echo "/run/WSL/${pid}_interop"
      return
    fi
  done
}

case $os in
  mac)
    exec git credential-osxkeychain "$@"
    ;;
  wsl)
    WSL_INTEROP=`show_correct_wsl_interop` exec /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe "$@"
  ;;
  linux)
    exec git credential-cache --timeout 86400 "$@"
  ;;
esac
