#!/usr/bin/env bash
set -euo pipefail

# HACK: tmux 内であることを検出した際 chalk.level を 3 (24bit RGB) から 2 (256色 量子化) にダウングレードしてしまう問題を回避
# ref. https://code.claude.com/docs/ja/env-vars
if [[ -n "${TMUX:-}" ]]; then
  export CLAUDE_CODE_TMUX_TRUECOLOR=1
fi

if [[ "${TERM_PROGRAM:-}" == vscode ]]; then
  # HACK: なぜ?
  # https://github.com/anthropics/claude-code/issues/35148
  export TERM_PROGRAM=
fi

exec claude --allow-dangerously-skip-permissions "$@"
