source ~/.config/exports

fpath=($XDG_DATA_HOME/zsh/functions(N-/) $fpath)

# SEE:
#   - /etc/zsh/zshrc
#   - http://fardinshikhiyev.github.io/Speed-up-your-oh-my-zsh/
skip_global_compinit=1

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

typeset -U path fpath
