onboarding = false

[update]
version_check = false

[terminal]
shell_mode = "login"
new_cwd = "follow"

[ui]
hide_tab_bar_when_single_tab = true
confirm_close = false
prompt_new_tab_name = false
host_cursor = "native"
sidebar_collapsed_mode = 'hidden'
sidebar.spaces.row_gap = 1
sidebar.agents.row_gap = 1
sidebar.agents.rows = [
  ["state_icon", "workspace", "tab"],
  [{ token = "agent", dim = false }],
]
pane_scrollbars = false

[keys]
prefix = "F8"
copy_mode = "prefix+y"
next_tab = "ctrl+tab"
previous_tab = "ctrl+shift+tab"
focus_pane_left = "ctrl+left"
focus_pane_down = "ctrl+down"
focus_pane_up = "ctrl+up"
focus_pane_right = "ctrl+right"
swap_pane_left = "ctrl+shift+left"
swap_pane_down = "ctrl+shift+down"
swap_pane_up = "ctrl+shift+up"
swap_pane_right = "ctrl+shift+right"
settings = "prefix+,"
split_vertical = "prefix+v"
split_horizontal = "prefix+s"

[[keys.command]]
key = "prefix+@"
type = "plugin_action"
command = "844196.file-picker.open"

[[keys.command]]
key = "prefix+space"
type = "plugin_action"
command = "844196.layout-pane.toggle"

[theme]
name = "tokyo-night"
auto_switch = false

[theme.custom]
panel_bg = "transparent" # tabbar background & modal background
accent = "#82aaff"
surface_dim = "#222436"  # sidebar border & scrollbar track
active_row_bg = "#222436" # sidebar active item background
overlay0 = "#414868" # inactive pane border & sidebar section fg & sidebar item subtext fg
overlay1 = "#2f334d"     # scrollbar thumb
