shell = 'zsh'

[templates]
load-config = 'source $ZDOTDIR/{{ name }}.config.zsh'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
rev = 'b46602d'

[plugins.undollar]
github = 'zpm-zsh/undollar'
rev = '5113cd0'

[plugins.zman]
github = 'mattmc3/zman'
rev = '40483a4'

# Must be after execution of fpath load and only need to call once
[plugins.compinit]
inline = '''
autoload -Uz compinit compute-compinit-options
local compdump=~/.cache/zsh/compdump
compinit $(compute-compinit-options --ttl $((60 * 60 * 24 * 7)) $compdump) -d $compdump
[[ ! -e ${compdump}.zwc || ${compdump}.zwc -ot $compdump ]] && zcompile $compdump
'''

# Must be loaded after loading all other plugins (except zsh-autosuggestions, see below)
[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
rev = 'b2c910a'
apply = ['source', 'load-config']

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions-pre]
inline = 'ZSH_AUTOSUGGEST_MANUAL_REBIND=1'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
rev = 'a411ef3'
apply = ['source', 'load-config']
