shell = "zsh"

[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
load-config = 'zsh-defer source ~/.config/{{ name }}/config.zsh'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "57a6650"

[plugins.compinit]
inline = "zsh-defer compinit -C -d ~/.cache/zsh/compdump"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
rev = "a411ef3"
apply = ["defer", "load-config"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
rev = "b2c910a"
apply = ["defer", "load-config"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
rev = "396c38a"
apply = ["defer"]
