shell = 'zsh'

[templates]
load-config = 'source $ZDOTDIR/{{ name }}.config.zsh'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
rev = 'b46602d'

[plugins.undollar]
github = 'zpm-zsh/undollar'
rev = '5113cd0'

[plugins.zman]
github = 'mattmc3/zman'
rev = '40483a4'

[plugins.zsh-async]
github = 'mafredri/zsh-async'
rev = 'ee1d11b'

[plugins.zsh-async-post]
inline = 'async_init'

# Must be after execution of fpath load and only need to call once
[plugins.compinit]
inline = '''
autoload -Uz compinit compute-compinit-options
local compdump=~/.cache/zsh/compdump
compinit $(compute-compinit-options --ttl $((60 * 60 * 24 * 7)) $compdump) -d $compdump
[[ ! -e ${compdump}.zwc || ${compdump}.zwc -ot $compdump ]] && zcompile $compdump
'''

# Avoid `cut` call
# see: https://github.com/hlissner/zsh-autopair/blob/396c38a7468458ba29011f2ad4112e4fd35f78e6/autopair.zsh#L5-L6
[plugins.zsh-autopair-pre]
inline = '''
AUTOPAIR_SPC_WIDGET=dot-expand-alias-and-self-insert
AUTOPAIR_BKSPC_WIDGET=backward-delete-char
'''

# Must be after execution compinit
# see: https://github.com/hlissner/zsh-autopair#zplug
[plugins.zsh-autopair]
github = 'hlissner/zsh-autopair'
rev = '396c38a'

# Must be loaded after loading all other plugins (except zsh-autosuggestions) and compinit
[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
rev = 'b2c910a'
apply = ['source', 'load-config']

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions-pre]
inline = 'ZSH_AUTOSUGGEST_MANUAL_REBIND=1'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
rev = 'a411ef3'
apply = ['source', 'load-config']
