shell = "zsh"

[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
defer-with-config = '''
zsh-defer -c '{% for file in files %}source "{{ file }}"; {% endfor %}source ~/.config/{{ name }}/config.zsh'
'''

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
rev = 'b46602d'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "57a6650"

[plugins.undollar]
github = 'zpm-zsh/undollar'
rev = '5113cd0'

# Must be after execution of fpath load and only need to call once
[plugins.compinit]
inline = "zsh-defer dot-compinit"

# Must be after execution compinit
# see: https://github.com/hlissner/zsh-autopair#zplug
[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
rev = "396c38a"
apply = ["defer"]

# Must be loaded after loading all other plugins (except zsh-autosuggestions) and compinit
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
rev = "b2c910a"
apply = ["defer-with-config"]

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions-pre]
inline = 'export ZSH_AUTOSUGGEST_MANUAL_REBIND=1'

# Must be initialized after zsh-syntax-highlighting
# see: https://github.com/zsh-users/zsh-autosuggestions/blob/a411ef3e0992d4839f0732ebeb9823024afaaaa8/src/start.zsh#L8-L13
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
rev = "a411ef3"
apply = ["defer-with-config"]
