shell = "zsh"

[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
load-config = '{% for file in files %}zsh-defer source ~/.config/{{ file }}/config.zsh{% endfor %}'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.compinit]
inline = "zsh-defer compinit -C -d ~/.cache/zsh/compdump"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer", "load-config"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer", "load-config"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]
