shell = "zsh"

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
rev = 'b46602d'

[plugins.undollar]
github = 'zpm-zsh/undollar'
rev = '5113cd0'

[plugins.zman]
github = 'mattmc3/zman'
rev = '40483a4'

# Must be after execution of fpath load and only need to call once
[plugins.compinit]
inline = '''
autoload -Uz compinit compute-compinit-options
local compdump=~/.cache/zsh/compdump
compinit $(compute-compinit-options --ttl $((60 * 60 * 24 * 7)) $compdump) -d $compdump
[[ ! -e ${compdump}.zwc || ${compdump}.zwc -ot $compdump ]] && zcompile $compdump
'''

# Must be after execution compinit
# see: https://github.com/hlissner/zsh-autopair#zplug
[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
rev = "396c38a"

# Must be loaded after loading all other plugins (except zsh-autosuggestions) and compinit
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
rev = "b2c910a"

[plugins.zsh-syntax-highlighting-config]
inline = 'source-config zsh-syntax-highlighting'

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions-pre]
inline = 'export ZSH_AUTOSUGGEST_MANUAL_REBIND=1'

# Must be initialized after zsh-syntax-highlighting
# see: https://github.com/zsh-users/zsh-autosuggestions/blob/a411ef3e0992d4839f0732ebeb9823024afaaaa8/src/start.zsh#L8-L13
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
rev = "a411ef3"

[plugins.zsh-autosuggestions-config]
inline = 'source-config zsh-autosuggestions'
