.local/share/zsh/vendor-completions/_task:
  type: file
  url: https://raw.githubusercontent.com/go-task/task/v3.31.0/completion/zsh/_task

.config/bat/themes/tokyonight_night/tokyonight_night.tmTheme:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/tags/v4.11.0/extras/sublime/tokyonight_night.tmTheme
  refreshPeriod: 168h

.local/share/mise/installer:
  type: file
  executable: true
  url: https://mise.run

.local/share/zsh/plugins/zman:
  type: archive
  exact: true
  url: https://github.com/mattmc3/zman/archive/40483a43f262698476d3d3c740c3c865e15ac01e.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/anyframe:
  type: archive
  exact: true
  url: https://github.com/mollifier/anyframe/archive/598675303044df8e9d04722f3adff4f63a238922.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/fast-syntax-highlighting:
  type: archive
  exact: true
  url: https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/cf318e06a9b7c9f2219d78f41b46fa6e06011fd9.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/zsh-autosuggestions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/0e810e5afa27acbd074398eefbe28d13005dbc15.tar.gz
  stripComponents: 1

.local/share/nvim/lazy/lazy.nvim:
  type: archive
  exact: true
  url: https://github.com/folke/lazy.nvim/archive/refs/tags/v11.17.5.tar.gz
  stripComponents: 1
