.local/share/zsh/vendor-completions/_task:
  type: file
  url: https://raw.githubusercontent.com/go-task/task/v3.31.0/completion/zsh/_task

.cache/gitmoji/gitmojis.json:
  type: file
  url: https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json
  refreshPeriod: 168h

.config/bat/themes/tokyonight_night/tokyonight_night.tmTheme:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/tags/v4.11.0/extras/sublime/tokyonight_night.tmTheme
  refreshPeriod: 168h

.cache/aquaproj-aqua/aqua-installer:
  type: file
  executable: true
  url: https://raw.githubusercontent.com/aquaproj/aqua-installer/v4.0.0/aqua-installer
  checksum.sha256: f7fa69dacb234ce9648f3008cef9120a1e59d96c37971e747668c0fada7bec68

.local/bin/mise:
  type: file
  executable: true
  url: https://github.com/jdx/mise/releases/download/v2025.9.25/mise-v2025.9.25-linux-x64-musl

.local/bin/wk:
  type: file
  executable: true
  url: https://github.com/844196/wk/releases/download/v1.0.2/wk-x86_64-unknown-linux-gnu

.local/share/zsh/plugins/zman:
  type: archive
  exact: true
  url: https://github.com/mattmc3/zman/archive/40483a43f262698476d3d3c740c3c865e15ac01e.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/anyframe:
  type: archive
  exact: true
  url: https://github.com/mollifier/anyframe/archive/598675303044df8e9d04722f3adff4f63a238922.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/fast-syntax-highlighting:
  type: archive
  exact: true
  url: https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/cf318e06a9b7c9f2219d78f41b46fa6e06011fd9.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/zsh-autosuggestions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/0e810e5afa27acbd074398eefbe28d13005dbc15.tar.gz
  stripComponents: 1

.neovim:
  type: archive
  exact: true
  url: https://github.com/neovim/neovim/releases/download/v0.11.3/nvim-linux-x86_64.tar.gz
  stripComponents: 1
