.local/share/zsh/vendor-completions/_task:
  type: file
  url: https://raw.githubusercontent.com/go-task/task/v3.31.0/completion/zsh/_task

.cache/gitmoji/gitmojis.json:
  type: file
  url: https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json
  refreshPeriod: 168h

.cache/aquaproj-aqua/aqua-installer:
  type: file
  executable: true
  url: https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.0.1/aqua-installer
  checksum.sha256: fb4b3b7d026e5aba1fc478c268e8fbd653e01404c8a8c6284fdba88ae62eda6a

.local/bin/mise:
  type: file
  executable: true
  url: https://github.com/jdx/mise/releases/download/v2024.12.5/mise-v2024.12.5-linux-x64-musl

.local/bin/wk:
  type: file
  executable: true
  url: https://github.com/844196/wk/releases/download/v0.4.2/wk-x86_64-unknown-linux-gnu

.local/share/zsh/plugins/zman:
  type: archive
  exact: true
  url: https://github.com/mattmc3/zman/archive/40483a43f262698476d3d3c740c3c865e15ac01e.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/anyframe:
  type: archive
  exact: true
  url: https://github.com/mollifier/anyframe/archive/598675303044df8e9d04722f3adff4f63a238922.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/fast-syntax-highlighting:
  type: archive
  exact: true
  url: https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/cf318e06a9b7c9f2219d78f41b46fa6e06011fd9.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/zsh-autosuggestions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/0e810e5afa27acbd074398eefbe28d13005dbc15.tar.gz
  stripComponents: 1
