.local/share/zsh/vendor-completions/_task:
  type: file
  url: https://raw.githubusercontent.com/go-task/task/v3.31.0/completion/zsh/_task

.cache/gitmoji/gitmojis.json:
  type: file
  url: https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json
  refreshPeriod: 168h

.cache/aquaproj-aqua/aqua-installer:
  type: file
  executable: true
  url: https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.0.1/aqua-installer
  checksum.sha256: fb4b3b7d026e5aba1fc478c268e8fbd653e01404c8a8c6284fdba88ae62eda6a

.local/bin/mise:
  type: file
  executable: true
  url: https://github.com/jdx/mise/releases/download/v2024.7.1/mise-v2024.7.1-linux-x64-musl
  checksum.sha256: 6c370b8535be0e8453a2ecc0652358e4728cf0c6f9c620d466edbf5ae9df4c58

.local/bin/wk:
  type: file
  executable: true
  url: https://github.com/844196/wk/releases/download/v0.0.3/wk-x86_64-unknown-linux-gnu

.local/share/zsh/plugins/zman:
  type: archive
  exact: true
  url: https://github.com/mattmc3/zman/archive/40483a43f262698476d3d3c740c3c865e15ac01e.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/zsh-completions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-completions/archive/7a884c75b4f3ce2d8d24df8e55dcc359a020be3f.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/anyframe:
  type: archive
  exact: true
  url: https://github.com/mollifier/anyframe/archive/598675303044df8e9d04722f3adff4f63a238922.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/fast-syntax-highlighting:
  type: archive
  exact: true
  url: https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/cf318e06a9b7c9f2219d78f41b46fa6e06011fd9.tar.gz
  stripComponents: 1

.local/share/zsh/plugins/zsh-autosuggestions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/c3d4e576c9c86eac62884bd47c01f6faed043fc5.tar.gz
  stripComponents: 1
