.config/bat/themes/tokyonight_night/tokyonight_night.tmTheme:
  type: file
  url: https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/tags/v{{ .versions.tokyonight }}/extras/sublime/tokyonight_night.tmTheme
  refreshPeriod: 168h

.local/share/mise/installer:
  type: file
  executable: true
  url: https://mise.run

.local/share/zman:
  type: archive
  exact: true
  url: https://github.com/mattmc3/zman/archive/40483a43f262698476d3d3c740c3c865e15ac01e.tar.gz
  stripComponents: 1

.local/share/anyframe:
  type: archive
  exact: true
  url: https://github.com/mollifier/anyframe/archive/598675303044df8e9d04722f3adff4f63a238922.tar.gz
  stripComponents: 1

.local/share/zsh-autosuggestions:
  type: archive
  exact: true
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/{{ .versions.zshAutosuggestions }}.tar.gz
  stripComponents: 1

.local/share/zsh-shift-select:
  type: archive
  exact: true
  url: https://github.com/jirutka/zsh-shift-select/archive/refs/tags/v0.1.1.tar.gz
  stripComponents: 1

.local/share/nvim/lazy/lazy.nvim:
  type: archive
  exact: true
  url: https://github.com/folke/lazy.nvim/archive/refs/tags/v11.17.5.tar.gz
  stripComponents: 1
