.local/share/zsh/vendor-completions/_task:
  type: file
  url: https://raw.githubusercontent.com/go-task/task/v3.31.0/completion/zsh/_task
  refreshPeriod: 168h

.cache/gitmoji/gitmojis.json:
  type: file
  url: https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json
  refreshPeriod: 168h

.cache/aquaproj-aqua/aqua-installer:
  type: file
  executable: true
  url: https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.0.1/aqua-installer
  checksum.sha256: fb4b3b7d026e5aba1fc478c268e8fbd653e01404c8a8c6284fdba88ae62eda6a
  refreshPeriod: 168h
