shell = 'zsh'

[plugins.anyframe]
github = 'mollifier/anyframe'
rev = '5986753'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
rev = 'b46602d'

[plugins.zman]
github = 'mattmc3/zman'
rev = '40483a4'

[plugins.completioninit]
inline = '''
completioninit

# 'rm *' の挙動を変化させずに、補完候補を探索するときだけドットファイルを含めるようにする
# https://www.reddit.com/r/zsh/comments/i3o2cq/show_hidden_files_but_hide_and_from_completion/
# HACK: Undocumentedかつ compinit 実行後に設定しないと効果がない
_comp_options+=(globdots)
'''

# Must be loaded after loading all other plugins (except zsh-autosuggestions, see below)
[plugins.fast-syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'
rev = 'cf318e0'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
rev = 'a411ef3'

# see: https://github.com/zsh-users/zsh-autosuggestions#disabling-automatic-widget-re-binding
[plugins.zsh-autosuggestions.hooks]
pre = 'ZSH_AUTOSUGGEST_MANUAL_REBIND=1'
post = '''
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(
  accept-line-with-expand-alias
  history-beginning-search-backward-end
  history-beginning-search-forward-end
  up-line-or-beginning-search
  down-line-or-beginning-search
)

function magic-space() {
  zle self-insert-with-expand-alias
  zle autosuggest-fetch
}

function magic-tab() {
  zle fzf-completion-or-expand-or-complete
  zle autosuggest-fetch
}

zle -N magic-space
zle -N magic-tab

bindkey ' ' magic-space
bindkey '^I' magic-tab
'''
