format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

right_format = "${custom.git_user}"

[character]
success_symbol = "[](bold fg:#454b68)"
error_symbol = "[](bold red)"

[username]
format = "[$user](fg:#748caf)"
show_always = true

[hostname]
format = "[@$hostname](fg:#748caf) [in](fg:#6b7089) "
ssh_only = false

[directory]
truncation_length = 0
truncate_to_repo = true
format = "[ $path](fg:#84a0c6)[$read_only]($read_only_style) "
read_only = " [READ_ONLY]"

[git_branch]
always_show_remote = true
format = "[on](fg:#6b7089) [שׂ $branch](purple) "

[git_status]
style = "purple"
conflicted = " "
untracked  = " "
stashed    = "﯏ "
modified   = " "
staged     = " "
renamed    = " "
deleted    = " "
ahead = " ${count}"
behind = " ${count}"
diverged = " ${ahead_count}  ${behind_count}"
format = "([$ahead_behind]($style) )([\\[$all_status\\]]($style) )"

[cmd_duration]
format = "[took](fg:#6b7089) [$duration]($style)"

[custom.git_user]
shell = ["bash", "--noprofile", "--norc", "-e"]
when = ":"
command = '''
user="$(git config --local user.name 2>/dev/null)"
echo " ${user}"
'''
format = "[$output](fg:#3d435c)"
